# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec23d4ab3622965792892bcafd68a344537b1196b702aefcab73213a2762343dc27b73a2162665f5f7443e031f90387ec1fc666702e7976732093497e8d868d2

test:
  secret_key_base: 5b18b379cc9a53f570b7690076d484d912e259ab4e1b13039ea3985ca156fe6f9ed513f98131db4c3533d1bc6d670db844b12a94a67e99b2bdd13da006ec262c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
